spring:
  config:
    activate:
      on-profile: local
  session:
    store-type: redis
  redis:
    host: ${LOCAL_REDIS_HOST}
    port: ${LOCAL_REDIS_PORT}
  datasource:
    url: jdbc:mysql://${MYSQL_URL}:${MYSQL_PORT}/${MYSQL_DBNAME}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
